# Generated by Django 2.2 on 2019-05-04 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20190504_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_account_set', to='finance.Account', verbose_name='З рахунку'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='on_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='on_account_set', to='finance.Account', verbose_name='На рахунок'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subcategories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.Subcategory', verbose_name='Підкатегорія'),
        ),
    ]
